# Generated by Django 5.0 on 2023-12-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trivia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triviaquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("History", "History"),
                    ("Geography", "Geography"),
                    ("Sports", "Sports"),
                    ("Music", "Music"),
                ],
                default="Science",
                max_length=100,
            ),
        ),
    ]
